# Generated by Django 6.0.6 on 2026-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.CharField()),
                ('author_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
