# Generated by Django 6.0.6 on 2026-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
