# Generated by Django 6.0.6 on 2026-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java', models.IntegerField(max_length=100)),
                ('python', models.IntegerField(max_length=100)),
                ('Linux', models.IntegerField(max_length=100)),
            ],
        ),
    ]
